name: ubuntu-18.04-omp

on:
  push:
    branches: [ master static ]
  pull_request:
    branches: [ master static ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake -DUSE_OPENMP=1 .. 
    - name: Compile
      working-directory: build
      run: make -j2

    - name: Run unit tests
      working-directory: build
      run: ctest -j2
